version: '3'
services:
  backend:
    image: node:transcendence
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./frontend/www:/app/www
