version: "3"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - trans
    restart: unless-stopped

  backend:
    image: node:${TAG}
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - CLIENT_PORT=${CLIENT_PORT}
      - SITE_URL=${SITE_URL}
      - FT_API_CLIENT_ID=${FT_API_CLIENT_ID}
      - FT_API_CLIENT_SECRET=${FT_API_CLIENT_SECRET}
      - FT_API_CALLBACK_URL=${FT_API_CALLBACK_URL}
      - NO_REPLY_EMAIL=${NO_REPLY_EMAIL}
      - NO_REPLY_EMAIL_HOST=${NO_REPLY_EMAIL_HOST}
      - NO_REPLY_EMAIL_PASS=${NO_REPLY_EMAIL_PASS}
    networks:
      - trans
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: nginx:${TAG}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${CLIENT_PORT}:80"
    networks:
      - trans
    depends_on:
      - backend
    restart: unless-stopped

networks:
  trans:
