version: "3"

services:
  backend:
    image: node:transcendence
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/app
      - ./frontend/www:/app/www
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - FT_API_CLIENT_ID=${FT_API_CLIENT_ID}
      - FT_API_CLIENT_SECRET=${FT_API_CLIENT_SECRET}
      - FT_API_CALLBACK_URL=${FT_API_CALLBACK_URL}
    networks:
      - trans
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - trans

networks:
  trans:
