FROM node:19

WORKDIR /app

RUN apt update \
	&& apt install -y zsh \
	&& sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

RUN npm i -g npm \
	&& npm i -g @nestjs/cli

CMD [ "/bin/bash" ]
